# Generated by Django 3.1 on 2021-01-05 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AziendaLingua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azienda', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'azienda',
                'verbose_name_plural': 'aziende',
                'db_table': 'azienda',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidati',
                'db_table': 'candidato',
            },
        ),
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=6, unique=True)),
                ('testo', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'domanda',
                'verbose_name_plural': 'domande',
                'db_table': 'domanda',
            },
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'lingua',
                'verbose_name_plural': 'lingue',
                'db_table': 'lingua',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'questionario',
                'verbose_name_plural': 'questionari',
                'db_table': 'questionario',
            },
        ),
        migrations.CreateModel(
            name='QuestionarioDomanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.PositiveSmallIntegerField()),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.domanda')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.questionario')),
            ],
            options={
                'verbose_name': 'questionario_domanda',
                'verbose_name_plural': 'questionari_domanda',
                'db_table': 'questionario_domanda',
                'unique_together': {('questionario', 'posizione'), ('questionario', 'domanda')},
            },
        ),
        migrations.CreateModel(
            name='Testo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=250)),
                ('slide', models.CharField(max_length=25)),
                ('posizione', models.CharField(max_length=25)),
                ('lingua', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'testo',
                'verbose_name_plural': 'testi',
                'db_table': 'testo',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=25)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
            ],
            options={
                'verbose_name': 'titolo',
                'verbose_name_plural': 'titoli',
                'db_table': 'titolo',
            },
        ),
        migrations.CreateModel(
            name='Esperienza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professione', models.CharField(max_length=25)),
                ('durata', models.IntegerField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
            ],
            options={
                'verbose_name': 'esperienza',
                'verbose_name_plural': 'esperienze',
                'db_table': 'eseperienza',
            },
        ),
        migrations.CreateModel(
            name='CandidatoParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.aziendalingua')),
            ],
            options={
                'verbose_name': 'candidato_parametro',
                'verbose_name_plural': 'candidato_parametri',
                'db_table': 'candidato_parametro',
            },
        ),
        migrations.CreateModel(
            name='CandidatoAzienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.aziendalingua')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
            ],
            options={
                'verbose_name': 'candidato_azienda',
                'verbose_name_plural': 'candidato_aziende',
                'db_table': 'candidato_azienda',
            },
        ),
        migrations.AddField(
            model_name='aziendalingua',
            name='lingua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.lingua'),
        ),
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('codicefiscale', models.CharField(max_length=10)),
                ('eta', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('stato', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('comune', models.CharField(max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
            ],
            options={
                'verbose_name': 'anagrafica',
                'verbose_name_plural': 'anagrafiche',
                'db_table': 'anagrafica',
            },
        ),
        migrations.CreateModel(
            name='Risposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutazione', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1)),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.questionariodomanda')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
            ],
            options={
                'verbose_name': 'risposta',
                'verbose_name_plural': 'risposte',
                'db_table': 'risposta',
                'unique_together': {('utente', 'domanda')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='aziendalingua',
            unique_together={('azienda', 'lingua')},
        ),
    ]
