# Generated by Django 3.1 on 2020-12-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=25)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
            ],
            options={
                'verbose_name': 'parametro',
                'verbose_name_plural': 'parametri',
                'db_table': 'parametro',
            },
        ),
    ]
