# Generated by Django 3.1 on 2020-11-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algoritmo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoritmo', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'algoritmo',
                'verbose_name_plural': 'algoritmi',
                'db_table': 'algoritmo',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utente', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'recruiter',
                'verbose_name_plural': 'recruiters',
                'db_table': 'recruiter',
            },
        ),
        migrations.CreateModel(
            name='AlgoritmoRecruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.BooleanField()),
                ('algoritmo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiter.algoritmo')),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.azienda')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiter.recruiter')),
            ],
            options={
                'verbose_name': 'algoritmo_recruiter',
                'verbose_name_plural': 'algoritmo_recruiters',
                'db_table': 'algoritmo_recruiter',
            },
        ),
        migrations.CreateModel(
            name='PrevisioneStraordinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsione', models.DecimalField(decimal_places=2, max_digits=5)),
                ('esito', models.BooleanField()),
                ('algoritmo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiter.algoritmo')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
            ],
            options={
                'verbose_name': 'previsione_straordinaria',
                'verbose_name_plural': 'previsioni_straordinari',
                'db_table': 'previsione_straordinaria',
                'unique_together': {('candidato', 'algoritmo')},
            },
        ),
        migrations.CreateModel(
            name='PrevisioneCorrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsione', models.DecimalField(decimal_places=2, max_digits=5)),
                ('esito', models.BooleanField()),
                ('algoritmo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiter.algoritmo')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quest.candidato')),
            ],
            options={
                'verbose_name': 'previsione_corrente',
                'verbose_name_plural': 'previsioni_corrente',
                'db_table': 'previsione_corrente',
                'unique_together': {('candidato', 'algoritmo')},
            },
        ),
    ]
